### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by nopp** [qk4l/zabbix-cachet#16]
I have this problem:

2017-07-26 14:19:58 -03 INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
2017-07-26 14:19:58 -03 INFO: (MainThread) Restart triggers_watcher worker
2017-07-26 14:19:58 -03 INFO: (Trigger Watcher) start trigger watcher

with python2

Exception in thread Trigger Watcher:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "zabbix-cachet.py", line 483, in triggers_watcher_worker
    triggers_watcher(service_map)
  File "zabbix-cachet.py", line 424, in triggers_watcher
    if zbx_event['acknowledged'] == '1':
TypeError: list indices must be integers, not str

with python3

Exception in thread Trigger Watcher:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "zabbix-cachet.py", line 483, in triggers_watcher_worker
    triggers_watcher(service_map)
  File "zabbix-cachet.py", line 424, in triggers_watcher
    if zbx_event['acknowledged'] == '1':
TypeError: list indices must be integers, not str

I put on line 424 a print to the zbx_event and get this:

[{'eventid': '2989272', 'value': '1', 'source': '0', 'clock': '1501093615', 'objectid': '17103', 'object': '0', 'acknowledged': '0', 'acknowledges': [], 'ns': '876343048'}]

Obs:. this happen when I have an incident, but, sometimes dont show this error and add on works fine.
Can you help ?

the same error with python3 and python2

**Comment by nopp** [comment]
the same error with python3 and python2

**Comment by nopp** [comment]
I think I found the "problem"

if zbx_event[0]['acknowledged'] == '1':


so, python is returning dict inside a list ... because this you need to get before a dict from list.

**Comment by nopp** [comment]
I sent to you a pull request with the fix :)

**Comment by qk4l** [comment]
Hi, 

Thank you for bug report and PR especially!
The bug was in _get_event_ method. It returned list it only one event had been registered for trigger.

**Comment by nopp** [comment]
Your fix is better than mine, I closed my PR :D.

**Comment by thyspir** [comment]
I got error "(MainThread) list indices must be integers or slices, not str" when use   ./zabbix-cachet.py .

==============================
root@cachetindo:/var/www/html/integrator/zabbix-cachet# ./zabbix-cachet.py 
2019-08-01 07:40:10 WIB INFO: (MainThread) Zabbix Cachet v.1.3.6 started
2019-08-01 07:40:10 WIB INFO: (MainThread) JSON-RPC Server Endpoint: https://zabbix.wowrack.com/zabbix/api_jsonrpc.php
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2019-08-01 07:40:11 WIB INFO: (MainThread) Zabbix ver: 3.2.11. Cachet ver: 2.3.14-dev
2019-08-01 07:40:12 WIB ERROR: (MainThread) list indices must be integers or slices, not str
==============================

I have cloned  the script twice and still get same error.
Could you let me know how to fix this error?
Thank you
