### ISSUE TITLE
Trigger Watcher - sometimes dont work

### ISSUE THREAD

**Issue by nopp** [qk4l/zabbix-cachet#19]
Hi,
I have some problems with Trigger Watcher, basically when I have some incident zabbix-cachet open an Incident on cachet, but sometimes dont close, but on zabbix the incident was closed some minutes a go. Trigger Watcher here check every 40 seconds.

With this problem I put a restart on cron to read again the information on zabbix.

**Comment by qk4l** [comment]
Hi,
> some minutes a go.

Is it a delay or incident does not update (close) at all?

**Comment by nopp** [comment]
Not update, I need restart zabbix-cachet to "read" again .. and update incident status.

**Comment by qk4l** [comment]
Please provide logs for investigation.

What version of Cachet do you use?

**Comment by nopp** [comment]
Here my zabbix-cachet-log
[log.zip](https://github.com/qk4l/zabbix-cachet/files/1207529/log.zip)

Im using the 2.3.12 cachet version.

**Comment by nopp** [comment]
You will see at the log, some restart every 1hour(to "fix").

**Comment by qk4l** [comment]
Thank you for log.

As I see sometimes Zabbix is not reachable and Trigger Watcher failed and die.

I'll fix it.

**Comment by vozerov** [comment]
@qk4l hello!

The same bug for me. Just more info from my side:

when zabbix triggers incident, zabbix-cachet successfully creates an incident in cachet:

`2017-08-25 15:25:02 MSK INFO: (Trigger Watcher) Incident Test is not reachable (id=7) was created for component id 39.`

Then i see logs that cachet checks incidents every 30 seconds (my config). And when incident gets resolved in zabbix, zabbix-cachet stopps monitoring at all... Just restart helps.

BTW, does zabbix-cachet automatically resolves incidents in cachet? Or triggers only?

Thanks.

**Comment by qk4l** [comment]
@nopp ,
Please update to 1.3.0 and check if problem gone.

**Comment by qk4l** [comment]
> BTW, does zabbix-cachet automatically resolves incidents in cachet? Or triggers only?

Yes it does.

> zabbix-cachet stopps monitoring at all.
Do you have a error or it just silently die?

**Comment by nopp** [comment]
@qk4l yes, I'll test :D

**Comment by nopp** [comment]
not working :(

**Comment by qk4l** [comment]
Please add debug log.

**Comment by nopp** [comment]
Sorry for the delay, Im testing again!

**Comment by nopp** [comment]
2017-10-04 15:02:00 -03 INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
2017-10-04 15:32:10 -03 INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
2017-10-04 15:44:35 -03 ERROR: (Trigger Watcher) Zabbix Error: ('Connection aborted.', BadStatusLine("''",))
2017-10-04 15:44:35 -03 ERROR: (Trigger Watcher) Cannot get value for trigger 17105

**Comment by nopp** [comment]
All not working now ... :( 
[zabbix-cache-error.log](https://github.com/qk4l/zabbix-cachet/files/1359087/zabbix-cache-error.log)

Now dont open incident.

See the log.

**Comment by nopp** [comment]
I rolled back to previous version with cron(to restart until 60minutes de zabbix-cachet to work).

**Comment by qk4l** [comment]
> Now dont open incident.

Oh! I forget to add some default values for templates. Fixed in 1.3.1.

The main problem is that request to Zabbix periodically failed with `BadStatusLine` exception 
```
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
Zabbix Error: ('Connection aborted.', BadStatusLine("''",))
```

In 1.3.0 version I added Zabbix ping check that and Watcher should not fail and die if Zabbix was not available or returned exceptions.

It's not a pill for the problem but it should helps to avoid such cases.

I made some googling and found that `BadStatusLine` can be raised in different cases:
1.  Web server on Zabbix side blocks clients by User-Agent
2.  Site works on https but http was configured

https://stackoverflow.com/questions/41024252/why-is-python-requests-throwing-this-badstatusline-exception
https://stackoverflow.com/questions/1767934/why-am-i-getting-this-error-in-python-httplib

**Comment by nopp** [comment]
2017-11-14 17:10:24 -02 INFO: (Trigger Watcher) Incident Database | Portalweb Pool (id=810) was created for component id 31.
Exception in thread Trigger Watcher:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "zabbix-cachet.py", line 583, in triggers_watcher_worker
    triggers_watcher(service_map)
  File "zabbix-cachet.py", line 499, in triggers_watcher
    message=inc_msg)
  File "zabbix-cachet.py", line 442, in upd_incident
    data = self._http_put(url, params)
  File "zabbix-cachet.py", line 239, in _http_put
    r = requests.put(url=url, json=params, headerhs=self.headers, verify=self.verify)
  File "/usr/lib/python3.4/dist-packages/requests/api.py", line 120, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python3.4/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'headerhs'

**Comment by nopp** [comment]
This problem on 1.3.2 :(

**Comment by nopp** [comment]
@qk4l

**Comment by qk4l** [comment]
I'm sorry it was mistype error =( 
_headerhs_  should be _headers_.
Fixed.

**Comment by nopp** [comment]
@qk4l I changed headerhs=self.headers to headers=self.headers, testing now ;)

**Comment by nopp** [comment]
2017-11-21 12:38:26 -02 INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
2017-11-21 12:39:39 -02 ERROR: (Trigger Watcher) ClientHttpError[http://status.preventsenior.io/api/v1/incidents, 401: {"errors":[{"id":"ae45a737-9b83-4b4e-a7bf-2b2fe0a70abd","status":401,"title":"Unauthorized","detail":"Authentication is required and has failed or has not yet been provided."}]}]
Exception in thread Trigger Watcher:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "zabbix-cachet.py", line 583, in triggers_watcher_worker
    triggers_watcher(service_map)
  File "zabbix-cachet.py", line 553, in triggers_watcher
    component_id=i['component_id'], component_status=comp_status)
  File "zabbix-cachet.py", line 427, in new_incidents
    incident_id=data['data']['id'],
TypeError: 'NoneType' object is not subscriptable

@qk4l

**Comment by qk4l** [comment]
It's weird... Have you updated from the repo?

**Comment by nopp** [comment]
@qk4l yes :|

**Comment by nopp** [comment]
@qk4l but I dont see in commits the fix of "headerhs"

**Comment by qk4l** [comment]
I forgot to push changes to right repo. Sorry about this.
